"set default 'runtimepath' (without ~/.vim folders)
"let &runtimepath = printf('%s/vimfiles,%s,%s/vimfiles/after', $VIM, $VIMRUNTIME, $VIM)

" what is the name of the directory containing this file?
let s:portable = expand('<sfile>:p:h')

" add the directory to 'runtimepath'
let &runtimepath = printf('%s,%s,%s/after', s:portable, &runtimepath, s:portable)


"---------- Keymaps ----------
let mapleader=","
imap jk <Esc>


"--------- Spacing ----------
set backspace=indent,eol,start
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set ve+=onemore


"---------- Syntax ----------
filetype indent plugin on
syntax on
"colorscheme elflord
"colorscheme vividchalk
colorscheme devastator
set nu
set nowrap
set foldenable
set foldmethod=indent
set foldnestmax=99
"set spell spelllang=en_us


"---------- Clipboard (Neovim) ----------
set clipboard+=unnamedplus
vnoremap  <leader>y  "+y
nnoremap  <leader>Y  "+yg_
nnoremap  <leader>y  "+y
nnoremap  <leader>yy  "+yy
nnoremap <leader>p "+p
nnoremap <leader>P "+P
vnoremap <leader>p "+p
vnoremap <leader>P "+P
