add-highlighter global/ number-lines
set-face global MatchingChar red,blue
addhl global/ show-matching default,default+b
map global insert <tab> '<a-;><gt>'
colorscheme solarized-dark
map global normal D '<a-l>d' -docstring 'delete to end of line'
map global normal Y '<a-l>y' -docstring 'yank to end of line'
map global normal '#' :comment-line<ret> -docstring 'comment line'
map global normal '<a-#>' :comment-block<ret> -docstring 'comment block'


# .editorconfig
hook global BufCreate .* %{editorconfig-load}


# jk for escape
hook global InsertChar k %{ try %{
  exec -draft hH <a-k>jk<ret> d
  exec <esc>
}}


# tab -> space
hook global InsertChar \t %{
  exec -draft -itersel h@
}
set-option global tabstop 4


# (MacOS) copy to system clipboard
hook global NormalKey y|d|c %{ nop %sh{
  printf %s "$kak_reg_dquote" | pbcopy
}}
