setw -g mouse off
set-option -g allow-rename off
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"
set -g focus-events on

# Hot reload
unbind 'r'
bind 'r' source-file ~/.tmux.conf

# Status bar
set -g status-style fg=gray39,bg=colour234

# Current working window
setw -g window-status-current-style "fg=colour46,bg=colour21,bold"       # acid
# setw -g window-status-current-style "fg=colour208,bg=colour234,bold"    # lasagana

# Command line
set -g message-style "fg=colour234,bg=colour46,fill=colour46"

# Selected row
set-window-option -g mode-style "fg=colour46,bg=colour21,bold"
set-window-option -g menu-selected-style "fg=colour46,bg=colour21,bold"

# Inactive separator
set -g pane-border-style "bg=default fg=gray27"

# Active separator
set -g pane-active-border-style "bg=default fg=lime"

# Key bindings
set-option -g prefix C-a
bind-key a send-prefix
bind-key C-a last-window
bind-key c  new-window -c "#{pane_current_path}"

# Splits
unbind 'P'
bind 'P' display-popup
unbind 'k'
bind 'k' confirm kill-window
unbind 'v'
bind-key 'v' split-window -h -c "#{pane_current_path}"
unbind 's'
bind-key 's' split-window -c "#{pane_current_path}"

# Movement
bind-key C-l select-pane -R
bind-key C-h select-pane -L
bind-key C-k select-pane -U
bind-key C-j select-pane -D

# Copy mode
bind-key C-u copy-mode

# Vi bindings in copy mode
setw -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection     # Begin selection in copy mode.
bind-key -T copy-mode-vi 'C-v' send -X rectangle-toggle  # Begin selection in copy mode.
bind-key -T copy-mode-vi 'y' send -X copy-selection      # Yank selection in copy
if-shell "uname | grep -q Linux" \
  'bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard"'

# Timeout display panes
set -g display-panes-time 5000

# Layouts
unbind '-'
bind '-' select-layout even-vertical
unbind '\'
bind '\' select-layout even-horizontal

# Terminal colors
set -s command-alias[100] "termcolor-danger=select-pane -P 'bg=colour52,fg=colour15'"
set -s command-alias[101] "termcolor-barney=select-pane -P 'bg=colour55,fg=colour123'"
set -s command-alias[102] "termcolor-bluebeetle=select-pane -P 'bg=colour17,fg=colour11'"
set -s command-alias[103] "termcolor-halloween=select-pane -P 'bg=colour0,fg=colour208'"
