setw -g mouse off
set-option -g allow-rename off
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"

# Status bar
set -g status-style bg=colour234,fg=darkgreen
setw -g window-status-current-style fg=colour118,bg=colour234

# Key bindings
set-option -g prefix C-a
bind-key a send-prefix
bind-key C-a last-window
bind-key c  new-window -c "#{pane_current_path}"

# Splits
bind P display-popup
bind k confirm kill-window
bind-key % split-window -h -c "#{pane_current_path}"
bind-key '"' split-window -c "#{pane_current_path}"

# Movement
bind-key C-l select-pane -R
bind-key C-h select-pane -L
bind-key C-k select-pane -U
bind-key C-j select-pane -D

# Copy mode
bind-key C-u copy-mode
