# ZSH HOME
export ZSH=$HOME/.config/zsh
export ZSH_PLUGIN_DIR=$ZSH/plugins
source $ZSH/forthismachineonly.zsh

# Use powerline
USE_POWERLINE="true"

# History config
touch $ZSH/.zsh_history
export HISTFILE=$ZSH/.zsh_history

# How many commands zsh will load to memory.
export HISTSIZE=10000

# How many commands history will save on file.
export SAVEHIST=10000

# History won"t save duplicates.
setopt HIST_IGNORE_ALL_DUPS

# History won"t show duplicates on search.
setopt HIST_FIND_NO_DUPS

# Case insensitve
autoload -Uz +X compinit && compinit
zstyle ":completion:*" matcher-list "m:{a-zA-Z}={A-Za-z}"
zstyle ":completion:*" menu select

# Vim mode
bindkey -v

# Plugins
source $ZSH/plugins.zsh
