# ZSH HOME
export ZSH=$HOME/.config/zsh
export ZSH_PLUGIN_DIR=$ZSH/plugins
source $ZSH/forthismachineonly.zsh

# Options
setopt correct                                                  # Auto correct mistakes
setopt extendedglob                                             # Extended globbing. Allows using regular expressions with *
setopt nocaseglob                                               # Case insensitive globbing
setopt rcexpandparam                                            # Array expension with parameters
setopt nocheckjobs                                              # Don't warn about running processes when exiting
setopt numericglobsort                                          # Sort filenames numerically when it makes sense
setopt nobeep                                                   # No beep
setopt appendhistory                                            # Immediately append history instead of overwriting
setopt histignorealldups                                        # If a new command is a duplicate, remove the older one
setopt autocd                                                   # if only directory path is entered, cd there.
setopt inc_append_history                                       # save commands are added to the history immediately, otherwise only when shell exits.
setopt histignorespace                                          # Don't save commands that start with space
setopt HIST_FIND_NO_DUPS                                        # explicitly prevent duplicates

# Use powerline
USE_POWERLINE="true"

# Extract the current Git branch name safely
parse_git_branch() {
    git branch 2> /dev/null | sed -n -e 's/^\* \(.*\)/(\1)/p'
}

# Enable parameter and command substitution in the prompt
setopt PROMPT_SUBST

# Prompt
PROMPT='%F{119}%B[%DT%*]%b%f %F{46}%4C%f %F{160}%B$(parse_git_branch)%b%f
%F{46}%B>%b%f '

# History config
touch $ZSH/.zsh_history
export HISTFILE=$ZSH/.zsh_history

# How many commands zsh will load to memory.
export HISTSIZE=10000

# How many commands history will save on file.
export SAVEHIST=10000

# History won't save duplicates.
setopt HIST_IGNORE_ALL_DUPS

# History won"t show duplicates on search.
setopt HIST_FIND_NO_DUPS

# Select from history
bindkey -e
bindkey '^[[7~' beginning-of-line                               # Home key
bindkey '^[[H' beginning-of-line                                # Home key
if [[ "${terminfo[khome]}" != "" ]]; then
  bindkey "${terminfo[khome]}" beginning-of-line                # [Home] - Go to beginning of line
fi
bindkey '^[[8~' end-of-line                                     # End key
bindkey '^[[F' end-of-line                                      # End key
if [[ "${terminfo[kend]}" != "" ]]; then
  bindkey "${terminfo[kend]}" end-of-line                       # [End] - Go to end of line
fi
bindkey '^[[2~' overwrite-mode                                  # Insert key
bindkey '^[[3~' delete-char                                     # Delete key
bindkey '^[[C'  forward-char                                    # Right key
bindkey '^[[D'  backward-char                                   # Left key
bindkey '^[[5~' history-beginning-search-backward               # Page up key
bindkey '^[[6~' history-beginning-search-forward                # Page down key

# Navigate words with ctrl+arrow keys
bindkey '^[Oc' forward-word                                     #
bindkey '^[Od' backward-word                                    #
bindkey '^[[1;5D' backward-word                                 #
bindkey '^[[1;5C' forward-word                                  #
bindkey '^H' backward-kill-word                                 # delete previous word with ctrl+backspace
bindkey '^[[Z' undo                                             # Shift+tab undo last action

# Vim mode
KEYTIMEOUT=20
EDITOR=$(which nvim)
bindkey -v
autoload edit-command-line
zle -N edit-command-line
bindkey -M vicmd '^f' edit-command-line
bindkey -M viins 'jk' vi-cmd-mode
bindkey -M viins '^[' vi-cmd-mode-fix   # also fixes plain Esc

# Set cursor location after last edit spot after esc
function vi-cmd-mode-fix {
  local cursor=$CURSOR
  zle .vi-cmd-mode
  CURSOR=$cursor
}
zle -N vi-cmd-mode-fix

# Enable fzf key bindings and auto-completion
source <(fzf --zsh)

# Plugins
source $ZSH/plugins.zsh
